trigger:
  - none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: package_link
    displayName: Linux Package URL
    type: string

jobs:
- deployment: VMDeploy
  displayName: BoldBI-Loadtest
  pool:
    vmImage: 'Ubuntu-latest'
  environment:
    name: loadtest-linux
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              cd ~
              ls
              echo 'triz3bl&aPrTC$jlphlf' | sudo -S mkdir loadtest
              cd loadtest
              sudo wget --no-check-certificate ${{parameters.package_link}}
              sudo unzip BoldBIEnterpriseEdition_Linux*
              cd BoldBIEnterpriseEdition-Linux
              if [ -d /var/www/bold-services ]; then
                echo "Upgrade Command"
                chmod +x install-boldbi.sh
                sudo bash install-boldbi.sh -i upgrade
              else
                echo "Fresh Installation"
                chmod +x install-boldbi.sh
                sudo bash install-boldbi.sh -i new -u root -h http://boldbi-loadtest.boldbi.com -n true
              fi
              cd ~
              sudo rm -rf loadtest