trigger:
- '*'

pool:
  vmImage: 'windows-latest'

jobs:
- job: UnzipLoadTestResults
  displayName: Unzip load test results and extract value
  steps:
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: 'D:\a\r1\a\_KingsleyAnbinnesan_jmeter_repo\apache-jmeter-5.5\bin\result.zip'
      destinationFolder: '$(Pipeline.Workspace)/loadtest-results'

  - task: PowerShell@2
    inputs:
      script: |
        $htmlFile = Get-ChildItem -Path $(Pipeline.Workspace)/loadtest-results/index.html
        $value = $(Invoke-WebRequest -Uri $htmlFile.Uri -Method Get -ContentType 'text/html' | Select-Xml -XPath '//*[@id="statisticsTable"]/tbody[2]/tr[1]/td[5]/text()' | Select-Object -ExpandProperty Value)
        Write-Host "The value is: $value"