trigger:
- '*'

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- powershell: |
    # Create a directory to store the HTML files if it doesn't exist
    mkdir -Force HTMLFiles

    # Copy the HTML file(s) from the result folder to the HTMLFiles directory
    Copy-Item -Path "$(System.DefaultWorkingDirectory)/_KingsleyAnbinnesan_jmeter_repo/apache-jmeter-5.5/bin/result/*.html" -Destination HTMLFiles/

    # Install the HTML Agility Pack library for parsing HTML (if not already installed)
    if (-not (Get-Module -Name 'HtmlAgilityPack' -ListAvailable)) {
        Install-Module -Name 'HtmlAgilityPack' -Scope CurrentUser -Force
    }

    # Load the HTML file and select the value using XPath
    $html = New-Object HtmlAgilityPack.HtmlDocument
    $html.Load("HTMLFiles/*.html")
    $value = $html.DocumentNode.SelectSingleNode("//*[@id='statisticsTable']/tbody[2]/tr[1]/td[5]").InnerText

    Write-Host "Extracted Value: $value"
    
    # Set the extracted value as an environment variable for later use
    Write-Host "##vso[task.setvariable variable=ExtractedValue;isOutput=true]$value"
    
  displayName: 'Extract Value from HTML'

- script: |
    # Use the extracted value in subsequent tasks or steps
    echo "The extracted value is $(ExtractedValue)"
