trigger:
- '*'

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'D:\a\r1\a\_KingsleyAnbinnesan_jmeter_repo\apache-jmeter-5.5\bin\result'  # Replace with the path to your existing zip folder
    artifact: 'loadtest'  # Replace with the desired name for your artifact

- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'loadtest'  # Replace with the name of your artifact
    path: $(System.ArtifactsDirectory)

- powershell: |
    # Navigate to the folder containing the HTML file
    Set-Location '$(System.ArtifactsDirectory)'

    # Use XPath to extract the desired value from the HTML file
    $xml = New-Object -TypeName XML
    $xml.Load('./index.html')  # Replace with the relative path to your HTML file within the unzipped folder
    $value = $xml.SelectSingleNode('//*[@id="statisticsTable"]/tbody[2]/tr[1]/td[5]').InnerText

    # Output the extracted value to a pipeline variable for future use
    Write-Host "Extracted Value: $value"
    Write-Output "##vso[task.setvariable variable=ExtractedValue;isOutput=true]$value"
  displayName: 'Extract Value'
